import { definePermissions } from "@robelest/convex-auth/permissions";

export const permissions = definePermissions({
  grants: [
    "projects.read",
    "projects.create",
    "projects.manage",
    "issues.create",
    "issues.edit",
    "issues.move",
    "issues.assign",
    "issues.delete",
    "comments.create",
    "comments.delete",
    "members.manage",
    "members.read",
    "workspace.settings",
    "connection.create",
    "connection.read",
    "connection.manage",
    "connection.domain.manage",
    "connection.protocol.manage",
    "connection.policy.manage",
    "connection.audit.read",
    "connection.webhook.manage",
    "scim.manage",
  ],
  roles: {
    orgAdmin: {
      label: "Admin",
      grants: [
        "projects.read",
        "projects.create",
        "projects.manage",
        "issues.create",
        "issues.edit",
        "issues.move",
        "issues.assign",
        "issues.delete",
        "comments.create",
        "comments.delete",
        "members.manage",
        "members.read",
        "workspace.settings",
        "connection.create",
        "connection.read",
        "connection.manage",
        "connection.domain.manage",
        "connection.protocol.manage",
        "connection.policy.manage",
        "connection.audit.read",
        "connection.webhook.manage",
        "scim.manage",
      ],
    },
    member: {
      label: "Member",
      grants: [
        "projects.read",
        "issues.create",
        "issues.edit",
        "issues.move",
        "comments.create",
        "members.read",
      ],
    },
    viewer: {
      label: "Viewer",
      grants: ["projects.read", "members.read"],
    },
  },
});

export const roles = permissions.roles;
