packages:
  - packages/*
  - demos/*
  - tests
  - docs

catalog:
  convex: ^1.41.0
  convex-test: ^0.0.48
  tsdown: 0.20.0-beta.3
  typescript: ^6.0.2
  vite: npm:@voidzero-dev/vite-plus-core@^0.1.13
  vite-plus: ^0.1.13
  vitest: npm:@voidzero-dev/vite-plus-test@latest
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
