/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoggedinRouteImport } from './routes/loggedin'

const IndexLazyRouteImport = createFileRoute('/')()

const LoggedinRoute = LoggedinRouteImport.update({
  id: '/loggedin',
  path: '/loggedin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/loggedin': typeof LoggedinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/loggedin': typeof LoggedinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/loggedin': typeof LoggedinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/loggedin'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/loggedin'
  id: '__root__' | '/' | '/loggedin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  LoggedinRoute: typeof LoggedinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/loggedin': {
      id: '/loggedin'
      path: '/loggedin'
      fullPath: '/loggedin'
      preLoaderRoute: typeof LoggedinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  LoggedinRoute: LoggedinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
