#!/usr/bin/env node

/**
 * Generates src/server/version.ts from package.json version.
 *
 * This file is imported by the Convex server code so the auth component
 * version is available at runtime (e.g. for the portal config endpoint).
 * The Convex bundler traces static imports, so this works in production.
 *
 * Usage: node scripts/generate-version.js
 * (Called automatically by `bun run build:version` in packages/auth/)
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgPath = join(__dirname, "..", "packages", "auth", "package.json");
const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));

const outPath = join(__dirname, "..", "packages", "auth", "src", "server", "version.ts");
const content = `// Auto-generated by scripts/generate-version.js — do not edit.\nexport const AUTH_VERSION = "${pkg.version}";\n`;

writeFileSync(outPath, content);
console.log(`Generated src/server/version.ts → v${pkg.version}`);
