const modules: Record<string, () => Promise<unknown>> = {
  "./component/_generated/api.ts": () => import("./_generated/api"),
  "./component/_generated/component.ts": () => import("./_generated/component"),
  "./component/_generated/dataModel.ts": () => import("./_generated/dataModel"),
  "./component/_generated/server.ts": () => import("./_generated/server"),
  "./component/convex.config.ts": () => import("./convex.config"),
  "./component/functions.ts": () => import("./functions"),
  "./component/http.ts": () => import("./http"),
  "./component/index.ts": () => import("./index"),
  "./component/model.ts": () => import("./model"),
  "./component/group.ts": () => import("./group"),
  "./component/group/member.ts": () => import("./group/member"),
  "./component/group/invite.ts": () => import("./group/invite"),
  "./component/user/key.ts": () => import("./user/key"),
  "./component/rateLimit.ts": () => import("./rateLimit"),
  "./component/account.ts": () => import("./account"),
  "./component/session.ts": () => import("./session"),
  "./component/token/refresh.ts": () => import("./token/refresh"),
  "./component/token/verification.ts": () => import("./token/verification"),
  "./component/token/pkce.ts": () => import("./token/pkce"),
  "./component/user.ts": () => import("./user"),
  "./component/user/email.ts": () => import("./user/email"),
  "./component/factor/passkey.ts": () => import("./factor/passkey"),
  "./component/factor/totp.ts": () => import("./factor/totp"),
  "./component/factor/device.ts": () => import("./factor/device"),
  "./component/sso/connection.ts": () => import("./sso/connection"),
  "./component/sso/connection/domain.ts": () => import("./sso/connection/domain"),
  "./component/sso/connection/domain/verification.ts": () =>
    import("./sso/connection/domain/verification"),
  "./component/sso/connection/secret.ts": () => import("./sso/connection/secret"),
  "./component/sso/connection/scimConfig.ts": () => import("./sso/connection/scimConfig"),
  "./component/sso/connection/scimIdentity.ts": () => import("./sso/connection/scimIdentity"),
  "./component/sso/audit.ts": () => import("./sso/audit"),
  "./component/sso/webhook/endpoint.ts": () => import("./sso/webhook/endpoint"),
  "./component/sso/webhook/delivery.ts": () => import("./sso/webhook/delivery"),
  "./component/schema.ts": () => import("./schema"),
};

export default modules;
