const modules: Record<string, () => Promise<unknown>> = {
  "./component/_generated/api.ts": () => import("./_generated/api"),
  "./component/_generated/component.ts": () => import("./_generated/component"),
  "./component/_generated/dataModel.ts": () => import("./_generated/dataModel"),
  "./component/_generated/server.ts": () => import("./_generated/server"),
  "./component/convex.config.ts": () => import("./convex.config"),
  "./component/functions.ts": () => import("./functions"),
  "./component/http.ts": () => import("./http"),
  "./component/index.ts": () => import("./index"),
  "./component/model.ts": () => import("./model"),
  "./component/public.ts": () => import("./public"),
  "./component/account.ts": () => import("./account"),
  "./component/session.ts": () => import("./session"),
  "./component/verificationCode.ts": () => import("./verificationCode"),
  "./component/refreshToken.ts": () => import("./refreshToken"),
  "./component/verifier.ts": () => import("./verifier"),
  "./component/user.ts": () => import("./user"),
  "./component/user/email.ts": () => import("./user/email"),
  "./component/public/factors/devices.ts": () => import("./public/factors/devices"),
  "./component/public/factors/passkeys.ts": () => import("./public/factors/passkeys"),
  "./component/public/factors/totp.ts": () => import("./public/factors/totp"),
  "./component/public/groups/core.ts": () => import("./public/groups/core"),
  "./component/public/groups/invites.ts": () => import("./public/groups/invites"),
  "./component/public/groups/members.ts": () => import("./public/groups/members"),
  "./component/public/security/keys.ts": () => import("./public/security/keys"),
  "./component/public/security/limits.ts": () => import("./public/security/limits"),
  "./component/public/sso/audit.ts": () => import("./public/sso/audit"),
  "./component/public/sso/core.ts": () => import("./public/sso/core"),
  "./component/public/sso/domains.ts": () => import("./public/sso/domains"),
  "./component/public/sso/scim.ts": () => import("./public/sso/scim"),
  "./component/public/sso/secrets.ts": () => import("./public/sso/secrets"),
  "./component/public/sso/webhooks.ts": () => import("./public/sso/webhooks"),
  "./component/schema.ts": () => import("./schema"),
};

export default modules;
